export const ART_STYLES = [
  {
    id: "watercolor",
    label: "Watercolor",
    prompt: `Soft watercolor illustration in the style of a premium children's picture book. STRICT RENDERING RULES: Use ONLY wet-on-wet watercolor technique on cold-pressed paper with visible paper texture throughout. EXACT COLOR PALETTE: dusty rose (#D4A0A0), sage green (#8FA88E), warm ochre (#D4A84B), soft periwinkle (#8E9FBF), and muted cream (#F5ECD7) — NO other colors allowed except black for faint ink outlines. All colors must appear at 40-60% opacity with visible pigment blooms and soft feathered edges where colors meet. LIGHTING: Soft diffused warm light from upper-left, casting gentle watercolor shadows in diluted blue-gray. CHARACTER DESIGN: All characters have round heads, dot eyes, small curved-line smiles, rosy circular cheeks in diluted pink. Hair is rendered as a single wash shape with no individual strands. Bodies are simple rounded forms with minimal detail. Every character must follow this EXACT same design template with NO variation between pages. BACKGROUND: Loose atmospheric washes with white paper showing through, minimal detail, dreamy unfocused quality.`,
  },
  {
    id: "pencil",
    label: "Colored Pencil",
    prompt: `Colored pencil illustration on cream textured paper, reminiscent of classic Beatrix Potter-era children's books. STRICT RENDERING RULES: ALL surfaces must show visible colored pencil crosshatch strokes at consistent 45-degree angles. No smooth digital gradients allowed. EXACT COLOR PALETTE: burnt sienna (#A0522D), goldenrod (#DAA520), forest green (#228B22), slate blue (#6A7FAF), warm brown (#8B6C42), and soft pink (#DEB0B0) — these EXACT colors only. LIGHTING: Warm golden light from the right side creating soft pencil-shaded shadows using layered brown and purple strokes. CHARACTER DESIGN: All characters have oval faces with small oval eyes (two dots with tiny white highlights), a tiny triangular nose, thin curved smile. Hair rendered in directional pencil strokes following the hair's flow. Simple clothing with visible pencil texture. Bodies are naturally proportioned but slightly simplified. Every character MUST follow this EXACT template with NO variation between pages. BACKGROUND: Lighter, less detailed pencil work with visible cream paper showing through, creating atmospheric depth.`,
  },
  {
    id: "papercut",
    label: "Paper Cutout",
    prompt: `Paper cutout collage illustration with layered construction-paper shapes. STRICT RENDERING RULES: Everything must look like it was physically cut from construction paper and glued down. Visible paper edges with slight shadows beneath each layer. NO gradients, NO blending — only flat solid-color paper shapes. EXACT COLOR PALETTE: cobalt blue (#0047AB), vermillion red (#E34234), sunny yellow (#FFD700), emerald green (#2E8B57), white, and kraft brown (#A0784A) background — these EXACT colors only. LIGHTING: Flat with subtle drop shadows (2px offset, 15% opacity black) beneath each paper layer to create depth. CHARACTER DESIGN: All characters are constructed from simple geometric paper shapes — circle heads, rectangle bodies, triangle details. Eyes are small punched-out circles (white with black dot). Mouths are thin curved paper strips. Hair is a single cut-paper shape. Limbs are simple rectangles with rounded ends. Every character MUST use this EXACT same geometric construction with NO variation between pages. BACKGROUND: Kraft paper texture base with layered paper landscape elements.`,
  },
  {
    id: "gouache",
    label: "Gouache",
    prompt: `Gouache painting in mid-century modern illustration style inspired by Mary Blair and Charley Harper. STRICT RENDERING RULES: All shapes painted with flat, opaque gouache — crisp hard edges, NO visible brush strokes, NO gradients within shapes. Colors are bold and unmodulated within each form. EXACT COLOR PALETTE: teal (#2A9D8F), coral (#E76F51), mustard (#E9C46A), charcoal (#264653), warm white (#FEFAE0), and muted plum (#7B506F) — these EXACT colors only. LIGHTING: Flat graphic lighting with no realistic shadows. Depth conveyed through color value and overlapping shapes only. CHARACTER DESIGN: All characters are highly stylized with geometric simplification — large oval or teardrop heads, tiny dot eyes placed close together, no visible nose, thin line smile. Bodies are bold simple shapes (triangles for dresses, rectangles for shirts). Hair is one solid shape. Strong silhouettes that read clearly at any size. Every character MUST follow this EXACT mid-century template with NO variation between pages. BACKGROUND: Flat color fields with bold geometric landscape forms, no texture.`,
  },
  {
    id: "digital",
    label: "Digital",
    prompt: `Clean digital illustration in contemporary children's book style inspired by Pixar concept art. STRICT RENDERING RULES: Smooth vector-like shapes with subtle cel-shading (maximum two value steps per surface). Gentle texture overlay at 5% opacity to avoid sterile look. Rounded, friendly forms everywhere. EXACT COLOR PALETTE: warm coral (#FF6B6B), soft teal (#4ECDC4), creamy yellow (#FFE66D), lavender (#C3AED6), warm charcoal (#2C3E50), and soft white (#F7F7F7) — these EXACT colors only. LIGHTING: Warm directional light from upper-left at 45 degrees. Key light in warm yellow-white, fill light in cool lavender. Soft cast shadows in desaturated purple (#9B8EC4) at 30% opacity. Rim lighting on character edges in pale yellow. CHARACTER DESIGN: All characters have large round heads (head-to-body ratio 1:2), big round eyes with large colored irises and prominent white catchlights, small rounded nose, wide friendly mouth. Smooth simple hair shapes. Rounded stubby limbs. Expressive but consistent proportions. Every character MUST follow this EXACT template with NO variation between pages. BACKGROUND: Soft blurred depth with warm atmospheric perspective.`,
  },
  {
    id: "crayon",
    label: "Crayon",
    prompt: `Crayon and chalk illustration on rough white drawing paper. STRICT RENDERING RULES: Everything must look drawn with actual wax crayons — thick textured strokes with visible waxy buildup, uneven coverage, and paper grain showing through ALL colored areas. NO clean edges, NO smooth fills. Strokes should be directional and energetic. EXACT COLOR PALETTE: cherry red (#DE3163), sky blue (#87CEEB), grass green (#4CAF50), sunshine yellow (#FFD54F), orange (#FF9800), and purple (#9C27B0) — these EXACT bright primary/secondary colors only. LIGHTING: No realistic lighting. Flat childlike rendering with a yellow crayon sun if outdoors. CHARACTER DESIGN: All characters drawn with thick black crayon outlines. Large circular heads with big round dot eyes, wide U-shaped smiles, stick-figure-inspired bodies with slightly thicker crayon-drawn limbs. Hair is scribbled crayon strokes. Rosy cheeks drawn as red crayon circles. Oversized heads on small bodies. Joyful, spontaneous, imperfect. Every character MUST follow this EXACT childlike template with NO variation between pages. BACKGROUND: Simple crayon-drawn elements — scribbly grass, basic cloud shapes, simple houses — with lots of white paper visible.`,
  },
];
